language: cpp
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - ./configure --enable-profile=gcov --with-compiler=gcc && make && make test
after_success:
  - coveralls --exclude rxp --exclude testsuite --exclude java

