language: cpp
matrix:
  include:
    - compiler: gcc
      before_install: sudo pip install cpp-coveralls --use-mirrors
      script: ./configure --enable-profile=gcov && make && make test
      after_success: coveralls --exclude rxp --exclude testsuite --exclude java
    - compiler: gcc
      env:
        global:
          # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
          #   via the "travis encrypt" command using the project repo's public key
          - secure: "FhoCOqzCeWJcXBFiYUNpo6wkje9kIyMayOm7t3HxgUpPcPENkh8KaG4CvgZkThC+4pMj62LCBTgEDWDAF+cANS3PgwviJaDhRWyV8VQU9MBVOTnRMnue7AphqMUZFBME8krLVzvHHPmAuNt+b04mWCitNlmURhdXFn5dedLme6E="
      addons:
        coverity_scan:
          project:
            name: "zeehio/speech-tools"
            description: "Code coverage for Speech Tools"
          notification_email: sergioller@gmail.com
          build_command_prepend: ./configure
          build_command: make
          branch_pattern: coverity_scan

